### ISSUE TITLE
[Feature Request] Support to Hide SystemBar (StatusBar + NavigationBar)

### ISSUE THREAD

**Issue by qiushui95** [dokar3/sheets#171]
First, thank you for your amazing work on the Sheets library. It has been incredibly useful for my project.

I would like to request a feature to hide the SystemBar (both the StatusBar and NavigationBar) when the application is in full-screen mode. This would enhance the user experience by providing a more immersive interface.

Currently, when using Sheets in full-screen mode, the SystemBar remains visible, which can be distracting for users. Having an option to automatically hide these bars would be a great addition.

Thank you for considering this feature request. Your efforts and contributions are greatly appreciated.

Thanks

**Comment by dokar3** [comment]
Thank you for your kind words! 

For the request, I would suggest using `CoreBottomSheetLayout` and controlling the system bars manually. Because there seems to be no easy way to get a fullscreen dialog when enabling the immersive mode, the space of the status bar still remains. 

If you know how to get rid of the status bar space, this snippet might also help:

```kotlin
BottomSheet(
    state = state,
    behaviors = DialogSheetBehaviors(
        extendsIntoStatusBar = true,
        extendsIntoNavigationBar = true,
    ),
) {
    val view = LocalView.current
    val window = (view.parent as DialogWindowProvider).window
    LaunchedEffect(view, window) {
        val insetsController = WindowCompat.getInsetsController(window, view)
        insetsController.systemBarsBehavior =
            WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
        insetsController.hide(WindowInsetsCompat.Type.systemBars())
    }

    // Content
}
```
